<div class="budicon-icon-acrobat" data-iconname="budicon-icon-acrobat" data-keys="acrobat"></div>
<div class="budicon-icon-amazon" data-iconname="budicon-icon-amazon" data-keys="amazon"></div>
<div class="budicon-icon-android" data-iconname="budicon-icon-android" data-keys="android"></div>
<div class="budicon-icon-angellist" data-iconname="budicon-icon-angellist" data-keys="angellist"></div>
<div class="budicon-icon-aol" data-iconname="budicon-icon-aol" data-keys="aol"></div>
<div class="budicon-icon-appnet" data-iconname="budicon-icon-appnet" data-keys="appnet"></div>
<div class="budicon-icon-appstore" data-iconname="budicon-icon-appstore" data-keys="appstore"></div>
<div class="budicon-icon-bitbucket" data-iconname="budicon-icon-bitbucket" data-keys="bitbucket"></div>
<div class="budicon-icon-bitcoin" data-iconname="budicon-icon-bitcoin" data-keys="bitcoin"></div>
<div class="budicon-icon-blogger" data-iconname="budicon-icon-blogger" data-keys="blogger"></div>
<div class="budicon-icon-buffer" data-iconname="budicon-icon-buffer" data-keys="buffer"></div>
<div class="budicon-icon-cal" data-iconname="budicon-icon-cal" data-keys="cal"></div>
<div class="budicon-icon-call" data-iconname="budicon-icon-call" data-keys="call"></div>
<div class="budicon-icon-cart" data-iconname="budicon-icon-cart" data-keys="cart"></div>
<div class="budicon-icon-chrome" data-iconname="budicon-icon-chrome" data-keys="chrome"></div>
<div class="budicon-icon-cloudapp" data-iconname="budicon-icon-cloudapp" data-keys="cloudapp"></div>
<div class="budicon-icon-creativecommons" data-iconname="budicon-icon-creativecommons" data-keys="creativecommons"></div>
<div class="budicon-icon-delicious" data-iconname="budicon-icon-delicious" data-keys="delicious"></div>
<div class="budicon-icon-digg" data-iconname="budicon-icon-digg" data-keys="digg"></div>
<div class="budicon-icon-disqus" data-iconname="budicon-icon-disqus" data-keys="disqus"></div>
<div class="budicon-icon-dribbble" data-iconname="budicon-icon-dribbble" data-keys="dribbble"></div>
<div class="budicon-icon-dropbox" data-iconname="budicon-icon-dropbox" data-keys="dropbox"></div>
<div class="budicon-icon-drupal" data-iconname="budicon-icon-drupal" data-keys="drupal"></div>
<div class="budicon-icon-dwolla" data-iconname="budicon-icon-dwolla" data-keys="dwolla"></div>
<div class="budicon-icon-email" data-iconname="budicon-icon-email" data-keys="email"></div>
<div class="budicon-icon-eventasaurus" data-iconname="budicon-icon-eventasaurus" data-keys="eventasaurus"></div>
<div class="budicon-icon-eventbrite" data-iconname="budicon-icon-eventbrite" data-keys="eventbrite"></div>
<div class="budicon-icon-eventful" data-iconname="budicon-icon-eventful" data-keys="eventful"></div>
<div class="budicon-icon-evernote" data-iconname="budicon-icon-evernote" data-keys="evernote"></div>
<div class="budicon-icon-facebook" data-iconname="budicon-icon-facebook" data-keys="facebook"></div>
<div class="budicon-icon-fivehundredpx" data-iconname="budicon-icon-fivehundredpx" data-keys="fivehundredpx"></div>
<div class="budicon-icon-flattr" data-iconname="budicon-icon-flattr" data-keys="flattr"></div>
<div class="budicon-icon-flickr" data-iconname="budicon-icon-flickr" data-keys="flickr"></div>
<div class="budicon-icon-forrst" data-iconname="budicon-icon-forrst" data-keys="forrst"></div>
<div class="budicon-icon-foursquare" data-iconname="budicon-icon-foursquare" data-keys="foursquare"></div>
<div class="budicon-icon-github" data-iconname="budicon-icon-github" data-keys="github"></div>
<div class="budicon-icon-gmail" data-iconname="budicon-icon-gmail" data-keys="gmail"></div>
<div class="budicon-icon-google" data-iconname="budicon-icon-google" data-keys="google"></div>
<div class="budicon-icon-googleplay" data-iconname="budicon-icon-googleplay" data-keys="googleplay"></div>
<div class="budicon-icon-googleplus" data-iconname="budicon-icon-googleplus" data-keys="googleplus"></div>
<div class="budicon-icon-gowalla" data-iconname="budicon-icon-gowalla" data-keys="gowalla"></div>
<div class="budicon-icon-grooveshark" data-iconname="budicon-icon-grooveshark" data-keys="grooveshark"></div>
<div class="budicon-icon-guest" data-iconname="budicon-icon-guest" data-keys="guest"></div>
<div class="budicon-icon-html5" data-iconname="budicon-icon-html5" data-keys="html5"></div>
<div class="budicon-icon-ie" data-iconname="budicon-icon-ie" data-keys="ie"></div>
<div class="budicon-icon-instagram" data-iconname="budicon-icon-instagram" data-keys="instagram"></div>
<div class="budicon-icon-instapaper" data-iconname="budicon-icon-instapaper" data-keys="instapaper"></div>
<div class="budicon-icon-intensedebate" data-iconname="budicon-icon-intensedebate" data-keys="intensedebate"></div>
<div class="budicon-icon-itunes" data-iconname="budicon-icon-itunes" data-keys="itunes"></div>
<div class="budicon-icon-klout" data-iconname="budicon-icon-klout" data-keys="klout"></div>
<div class="budicon-icon-lanyrd" data-iconname="budicon-icon-lanyrd" data-keys="lanyrd"></div>
<div class="budicon-icon-lastfm" data-iconname="budicon-icon-lastfm" data-keys="lastfm"></div>
<div class="budicon-icon-lego" data-iconname="budicon-icon-lego" data-keys="lego"></div>
<div class="budicon-icon-linkedin" data-iconname="budicon-icon-linkedin" data-keys="linkedin"></div>
<div class="budicon-icon-lkdto" data-iconname="budicon-icon-lkdto" data-keys="lkdto"></div>
<div class="budicon-icon-logmein" data-iconname="budicon-icon-logmein" data-keys="logmein"></div>
<div class="budicon-icon-macstore" data-iconname="budicon-icon-macstore" data-keys="macstore"></div>
<div class="budicon-icon-meetup" data-iconname="budicon-icon-meetup" data-keys="meetup"></div>
<div class="budicon-icon-myspace" data-iconname="budicon-icon-myspace" data-keys="myspace"></div>
<div class="budicon-icon-ninetyninedesigns" data-iconname="budicon-icon-ninetyninedesigns" data-keys="ninetyninedesigns"></div>
<div class="budicon-icon-openid" data-iconname="budicon-icon-openid" data-keys="openid"></div>
<div class="budicon-icon-opentable" data-iconname="budicon-icon-opentable" data-keys="opentable"></div>
<div class="budicon-icon-paypal" data-iconname="budicon-icon-paypal" data-keys="paypal"></div>
<div class="budicon-icon-persona" data-iconname="budicon-icon-persona" data-keys="persona"></div>
<div class="budicon-icon-pinboard" data-iconname="budicon-icon-pinboard" data-keys="pinboard"></div>
<div class="budicon-icon-pinterest" data-iconname="budicon-icon-pinterest" data-keys="pinterest"></div>
<div class="budicon-icon-plancast" data-iconname="budicon-icon-plancast" data-keys="plancast"></div>
<div class="budicon-icon-plurk" data-iconname="budicon-icon-plurk" data-keys="plurk"></div>
<div class="budicon-icon-pocket" data-iconname="budicon-icon-pocket" data-keys="pocket"></div>
<div class="budicon-icon-podcast" data-iconname="budicon-icon-podcast" data-keys="podcast"></div>
<div class="budicon-icon-posterous" data-iconname="budicon-icon-posterous" data-keys="posterous"></div>
<div class="budicon-icon-print" data-iconname="budicon-icon-print" data-keys="print"></div>
<div class="budicon-icon-quora" data-iconname="budicon-icon-quora" data-keys="quora"></div>
<div class="budicon-icon-reddit" data-iconname="budicon-icon-reddit" data-keys="reddit"></div>
<div class="budicon-icon-rss" data-iconname="budicon-icon-rss" data-keys="rss"></div>
<div class="budicon-icon-scribd" data-iconname="budicon-icon-scribd" data-keys="scribd"></div>
<div class="budicon-icon-skype" data-iconname="budicon-icon-skype" data-keys="skype"></div>
<div class="budicon-icon-smashing" data-iconname="budicon-icon-smashing" data-keys="smashing"></div>
<div class="budicon-icon-songkick" data-iconname="budicon-icon-songkick" data-keys="songkick"></div>
<div class="budicon-icon-soundcloud" data-iconname="budicon-icon-soundcloud" data-keys="soundcloud"></div>
<div class="budicon-icon-spotify" data-iconname="budicon-icon-spotify" data-keys="spotify"></div>
<div class="budicon-icon-stackoverflow" data-iconname="budicon-icon-stackoverflow" data-keys="stackoverflow"></div>
<div class="budicon-icon-statusnet" data-iconname="budicon-icon-statusnet" data-keys="statusnet"></div>
<div class="budicon-icon-steam" data-iconname="budicon-icon-steam" data-keys="steam"></div>
<div class="budicon-icon-stripe" data-iconname="budicon-icon-stripe" data-keys="stripe"></div>
<div class="budicon-icon-stumbleupon" data-iconname="budicon-icon-stumbleupon" data-keys="stumbleupon"></div>
<div class="budicon-icon-tumblr" data-iconname="budicon-icon-tumblr" data-keys="tumblr"></div>
<div class="budicon-icon-twitter" data-iconname="budicon-icon-twitter" data-keys="twitter"></div>
<div class="budicon-icon-viadeo" data-iconname="budicon-icon-viadeo" data-keys="viadeo"></div>
<div class="budicon-icon-vimeo" data-iconname="budicon-icon-vimeo" data-keys="vimeo"></div>
<div class="budicon-icon-vk" data-iconname="budicon-icon-vk" data-keys="vk"></div>
<div class="budicon-icon-weibo" data-iconname="budicon-icon-weibo" data-keys="weibo"></div>
<div class="budicon-icon-wikipedia" data-iconname="budicon-icon-wikipedia" data-keys="wikipedia"></div>
<div class="budicon-icon-windows" data-iconname="budicon-icon-windows" data-keys="windows"></div>
<div class="budicon-icon-wordpress" data-iconname="budicon-icon-wordpress" data-keys="wordpress"></div>
<div class="budicon-icon-xing" data-iconname="budicon-icon-xing" data-keys="xing"></div>
<div class="budicon-icon-yahoo" data-iconname="budicon-icon-yahoo" data-keys="yahoo"></div>
<div class="budicon-icon-ycombinator" data-iconname="budicon-icon-ycombinator" data-keys="ycombinator"></div>
<div class="budicon-icon-yelp" data-iconname="budicon-icon-yelp" data-keys="yelp"></div>
<div class="budicon-icon-youtube" data-iconname="budicon-icon-youtube" data-keys="youtube"></div>
